name             'static_webpages'
maintainer       'Edric Kyauk'
maintainer_email 'ekyauk@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures static_webpages'
long_description 'Installs/Configures static_webpages'
version          '0.1.0'
